# Generated by Django 4.2 on 2023-06-01 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenscore',
            name='garden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garden.garden'),
        ),
        migrations.AlterField(
            model_name='gardenscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
