# Generated by Django 4.2 on 2023-06-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garden', '0001_initial'),
        ('scores', '0002_alter_gardenscore_garden_alter_gardenscore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenscore',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.garden'),
        ),
        migrations.AlterField(
            model_name='gardenscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gardenscore',
            unique_together={('garden', 'user')},
        ),
    ]
