# Generated by Django 4.2 on 2023-06-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_gardenscore_garden_alter_gardenscore_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenscore',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 19, 44, 20, 100169)),
        ),
    ]
