# Generated by Django 4.2 on 2023-06-01 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_gardenscore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenscore',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 20, 0, 57, 171300)),
        ),
    ]
