# Generated by Django 4.2 on 2023-06-01 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_gardenscore_date_alter_gardenscore_garden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenscore',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 20, 30, 23, 671312)),
        ),
    ]
