# Generated by Django 4.2 on 2023-06-01 20:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garden', '0002_alter_garden_profile_photo'),
        ('scores', '0007_alter_gardenscore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenscore',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 2, 0, 19, 16, 590489)),
        ),
        migrations.AlterField(
            model_name='gardenscore',
            name='garden',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='garden.garden'),
        ),
        migrations.AlterField(
            model_name='gardenscore',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
