# Generated by Django 4.2 on 2023-05-29 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('business_code', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('avg_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('location', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
