# Generated by Django 4.2 on 2023-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
