# Generated by Django 4.2 on 2023-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/garden/images/'),
        ),
    ]
