# Generated by Django 4.2 on 2023-05-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='profile',
            new_name='profile_photo',
        ),
    ]
