# Generated by Django 4.2 on 2023-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plant_main_img_alter_plant_wikipedia_link'),
        ('garden', '0002_rename_profile_garden_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='plants',
            field=models.ManyToManyField(to='plants.plant'),
        ),
    ]
