# Generated by Django 4.2 on 2023-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_alter_garden_business_code_alter_garden_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
