# Generated by Django 4.2 on 2023-05-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_alter_plantimage_img'),
        ('garden', '0003_garden_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='plants',
            field=models.ManyToManyField(blank=True, null=True, to='plants.plant'),
        ),
    ]
