# Generated by Django 4.2 on 2023-05-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_temporaryuser_is_garden_owner'),
        ('garden', '0005_alter_garden_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='garden_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garden', to='accounts.gardenownerprofile'),
        ),
    ]
