# Generated by Django 4.2 on 2023-05-31 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_alter_garden_address_alter_garden_avg_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='garden',
            name='business_code',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='garden',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
