# Generated by Django 4.2 on 2023-06-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='allergy_compatible',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='attention_need',
            field=models.PositiveIntegerField(choices=[(1, 'Everyday'), (2, 'Weekly'), (3, 'Monthly')], default=None),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='light_condition',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=None),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='location_type_condition',
            field=models.PositiveIntegerField(choices=[(1, 'Apartment'), (2, 'Close'), (3, 'Open')], default=None),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='pet_compatible',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='saved_plants',
            field=models.ManyToManyField(blank=True, to='plants.plant'),
        ),
    ]
