# Generated by Django 4.2 on 2023-06-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenownerprofile',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='garden_license_pics'),
        ),
    ]
