# Generated by Django 4.2 on 2023-05-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normaluser_gardenownerprofile_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GardenOwnerProfile',
            new_name='GardenOwner',
        ),
        migrations.DeleteModel(
            name='GardenOwner',
        ),
        migrations.CreateModel(
            name='GardenOwnerProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.normaluser',),
        ),
    ]
