# Generated by Django 4.2 on 2023-05-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_gardenownerprofile_gardenowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.IntegerField()),
                ('business_id', models.IntegerField()),
                ('license', models.ImageField(upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
