# Generated by Django 4.2 on 2023-06-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_normaluser_allergy_compatible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='allergy_compatible',
            new_name='have_allergy',
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='pet_compatible',
            new_name='have_pet',
        ),
    ]
