# Generated by Django 4.2 on 2023-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gardenowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenowner',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
