# Generated by Django 4.2 on 2023-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_gardenowner_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenowner',
            name='business_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gardenowner',
            name='national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
