# Generated by Django 4.2 on 2023-05-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_gardenowner_business_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GardenOwner',
            new_name='GardenOwnerProfile',
        ),
        migrations.DeleteModel(
            name='GardenOwnerProxy',
        ),
        migrations.CreateModel(
            name='GardenOwner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.normaluser',),
        ),
    ]
