# Generated by Django 4.2 on 2023-05-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_gardenowner_gardenownerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='last_name',
        ),
    ]
