# Generated by Django 4.2 on 2023-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintenance', models.CharField(max_length=50)),
                ('fragrance', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('light_intensity', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('location_type', models.CharField(max_length=50)),
                ('water_need', models.IntegerField()),
                ('growth', models.IntegerField()),
                ('pet_compatible', models.BooleanField()),
                ('allergy_compatible', models.BooleanField()),
                ('attention_need', models.IntegerField()),
                ('edible', models.BooleanField()),
                ('wikipedia_link', models.URLField()),
                ('special_condition', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
