# Generated by Django 4.2 on 2023-05-24 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='plants',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plants',
            name='season',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='plants',
            name='attention_need',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
