# Generated by Django 4.2 on 2023-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plants_maintenance_plants_is_seasonal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
    ]
