# Generated by Django 4.2 on 2023-05-24 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_light_intensity_alter_plant_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='attention_need',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
