# Generated by Django 4.2 on 2023-05-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_attention_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='water_need',
        ),
        migrations.AddField(
            model_name='plant',
            name='main_img',
            field=models.ImageField(default=None, upload_to='./plants/Main_images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='maintenance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='water',
            field=models.PositiveIntegerField(choices=[(1, 'Everyday'), (2, 'Each two day'), (3, 'Once a week'), (4, 'Each two weeks')], default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='attention_need',
            field=models.PositiveIntegerField(choices=[(1, 'Everyday'), (2, 'Weekly'), (3, 'Monthly')], default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth',
            field=models.PositiveIntegerField(choices=[(1, 'Seed'), (2, 'Sapling'), (3, 'Complete')], default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_intensity',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location_type',
            field=models.PositiveIntegerField(choices=[(1, 'Apartment'), (2, 'Close'), (3, 'Open')], default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='season',
            field=models.PositiveIntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')], default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='special_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature',
            field=models.PositiveIntegerField(choices=[(1, 'Warm'), (2, 'Sultry')], default=1),
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./plants/images/')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
