# Generated by Django 4.2 on 2023-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_plant_main_image_remove_plant_water_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Prickly'), (2, 'With Flower'), (3, 'Flowerless')], default=1),
        ),
    ]
