# Generated by Django 4.2 on 2023-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
