# Generated by Django 4.2 on 2023-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_plant_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='./plants/Main_images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
