# Generated by Django 4.2 on 2023-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plant_main_img_alter_plant_wikipedia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/plants/main_images/'),
        ),
    ]
