# Generated by Django 4.2 on 2023-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_plant_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='img',
            field=models.ImageField(upload_to='static/plants/images/'),
        ),
    ]
